In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset=pd.read_csv("https://raw.githubusercontent.com/bhabani24/Linear-Regression-datasets/main/Admission_Prediction.csv")
dataset

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [3]:
#checking for null values
dataset.isnull().sum()

Serial No.            0
GRE Score            15
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [6]:
# filling null values with mean or median or mode
mode_value=dataset['GRE Score'].mode()[0]
dataset['GRE Score'].fillna(mode_value, inplace=True)
dataset['GRE Score']

mode1_value=dataset['TOEFL Score'].mode()[0]
dataset['TOEFL Score'].fillna(mode1_value,inplace=True)
dataset['TOEFL Score']

mean_value=dataset['University Rating'].mean()
dataset['University Rating'].fillna(mean_value,inplace=True)
dataset['University Rating']

0      4.0
1      4.0
2      3.0
3      3.0
4      2.0
      ... 
495    5.0
496    5.0
497    5.0
498    4.0
499    4.0
Name: University Rating, Length: 500, dtype: float64

In [7]:
# again checking for null values
dataset.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [8]:
# checking for categorical variables
dataset.dtypes

Serial No.             int64
GRE Score            float64
TOEFL Score          float64
University Rating    float64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [9]:
# removing unnecessary columns(serial no column)
dataset.drop('Serial No.',axis=1,inplace=True)

In [10]:
dataset

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0        337.0        118.0                4.0  4.5  4.5  9.65         1   
1        324.0        107.0                4.0  4.0  4.5  8.87         1   
2        312.0        104.0                3.0  3.0  3.5  8.00         1   
3        322.0        110.0                3.0  3.5  2.5  8.67         1   
4        314.0        103.0                2.0  2.0  3.0  8.21         0   
..         ...          ...                ...  ...  ...   ...       ...   
495      332.0        108.0                5.0  4.5  4.0  9.02         1   
496      337.0        117.0                5.0  5.0  5.0  9.87         1   
497      330.0        120.0                5.0  4.5  5.0  9.56         1   
498      312.0        103.0                4.0  4.0  5.0  8.43         0   
499      327.0        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [11]:
x=dataset.iloc[:,:7].values
y=dataset.iloc[:,7].values

In [12]:
x

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [312.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 120.  ,   5.  , ...,   5.  ,   9.56,   1.  ],
       [312.  , 103.  ,   4.  , ...,   5.  ,   8.43,   0.  ],
       [327.  , 113.  ,   4.  , ...,   4.5 ,   9.04,   0.  ]])

In [13]:
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [15]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [16]:
y_pred=model.predict(x_test)
y_pred

array([0.92963744, 0.72700342, 0.5409066 , 0.96928893, 0.55445493,
       0.62269073, 0.80659131, 0.58472617, 0.50672471, 0.63072863,
       0.62281878, 0.55208147, 0.49432745, 0.71412301, 0.53170155,
       0.69134017, 0.52962005, 0.63583991, 0.77340055, 0.88818338,
       0.87360668, 0.767208  , 0.67678843, 0.47519699, 0.78373003,
       0.88422002, 0.73784767, 0.69991634, 0.59085292, 0.61754015,
       0.73109372, 0.97751914, 0.50480502, 0.95528137, 0.68926273,
       0.72501203, 0.79029286, 0.7977266 , 0.6505409 , 0.69801986,
       0.82809791, 0.9611765 , 0.78441433, 0.9353456 , 0.58936088,
       0.75934295, 0.76685287, 0.99603072, 0.88762356, 0.78723198,
       0.61016819, 0.54114756, 0.91430637, 0.68868122, 0.73410496,
       0.55260589, 0.92700664, 0.73628384, 0.99508473, 0.75703832,
       0.60244236, 0.71578849, 0.7078517 , 0.94771233, 0.7023489 ,
       0.67693246, 0.72355625, 0.79087531, 0.65018921, 0.74950511,
       0.65800196, 0.57840945, 0.62060145, 0.90373095, 0.84054

In [17]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)


In [18]:
print("model coefficient:", model.coef_)
print("model intercept:", model.intercept_)

print("mean_squared_error:", mse)
print("r2_score:",r2)

model coefficient: [0.00194315 0.00306589 0.00417656 0.00242221 0.01833202 0.11680879
 0.02643119]
model intercept: -1.322454008055666
mean_squared_error: 0.004412180462263645
r2_score: 0.7935528392218755
